<html>
<head>
    <title>Sistema ERP</title>

    <style type="text/css">

    #loading-mask{
        background-color:white;
        height:100%;
        position:absolute;
        left:0;
        top:0;
        width:100%;
        z-index:20000;
    }
    #loading{
        height:auto;
        position:absolute;
        left:45%;
        top:40%;
        padding:2px;
        z-index:20001;
    }
    #loading a {
        color:#225588;
    }
    #loading .loading-indicator{
        background:white;
        color:#444;
        font:bold 13px Helvetica, Arial, sans-serif;
        height:auto;
        margin:0;
        padding:10px;
    }
    #loading-msg {
        font-size: 10px;
        font-weight: normal;
    }

    </style>
</head>
<body class="x-border-layout-ct">
    <div id="loading-mask" style=""></div>
    <div id="loading">
        <div class="loading-indicator">
            <img src="/extjs/images/extanim32.gif" width="32" height="32" style="margin-right:8px;float:left;vertical-align:top;"/>Sistema ERP
            <br /><span id="loading-msg">Carregando estilos e imagens...</span>
        </div>
    </div>

    <div id="viewport">
            <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/extjs/extjs/resources/css/ext-all.css');?>
            
            <script type="text/javascript">document.getElementById('loading-msg').innerHTML = 'Carregando API...';</script>
            <?php echo $this->headScript()->prependFile($this->basePath() . '/extjs/extjs/ext-all-debug.js'); ?>
            <script type="text/javascript">document.getElementById('loading-msg').innerHTML = 'Carregando Componenetes...';</script>
            <script type="text/javascript">document.getElementById('loading-msg').innerHTML = 'Inicializando...';</script>

            <!-- App.js contains Ext.App, a simple, re-usable Application component -->
            <script type="text/javascript" src="/extjs/app.js"></script>
    </div><!-- end viewport -->

</body>
</html>